### PR TITLE
fixed README.md typo

### PR DESCRIPTION
**Pull request by bubo-py**
Signed-off-by: bubo-py kamil.chruscinski1@gmail.com

## Description
This PR fixes typo in README.md

## Notes for Reviewers
they are defines -> they are defined

### CODE REVIEW

**Comment by bubo-py** [comment]
Created another one PR, but unfortunately it did not resolve the DCO problem. Sorry for that!

**Comment by tripathyprateek** [comment]
Hi @bubo-py .Thank you for fixing the typo. 
To fix the issue here, you need to run 2 commands in the terminal `git commit --amend --signoff` and then `git push --force-with-lease origin patch-2` to fix the DCO.

**Comment by bubo-py** [comment]
Hello @tripathyprateek. I run into an error below every time I try to push my changes, doesn't matter with which additional option. Could you please help?

```error: src refspec patch-2 does not match any```

**Comment by tripathyprateek** [comment]
Do you remember running the 2 commands in the same place where you opened this PR from. I guess this problem stems from that. Otherwise we can go ahead and merge this PR without the DCO check as well. No problem with that.

Next time when you make a commit in your file, instead of running `git commit -m "commit message here"` add a -s in front. For ex- `git commit -s -m "commit message here"`. Doing this passes the DCO check during commits, and you dont have to force push to pass DCO next time.

**Comment by bubo-py** [comment]
Okay, thank you. Let's add it then without DCO. I think the problem may be that I proposed changes directly from the browser - editing README.md in the Github repo. I haven't done anything locally since the change is minor.

**Comment by leecalcote** [comment]
> Okay, thank you. Let's add it then without DCO. I think the problem may be that I proposed changes directly from the browser - editing README.md in the Github repo. I haven't done anything locally since the change is minor.

@bubo-py, you're right. This is the cause of the DCO failure. It's a shame that GitHub's web interface doesn't support this. Adding to @tripathyprateek's great feedback, here is a link to the specific commands to correct this particular PR - https://github.com/layer5io/learn-layer5/pull/73/checks?check_run_id=1676656166

Given the nature of the change and the fact that this repo is less sensitive to mandating DCO, we can forego the requirement and move forward with merging this fix.

Thanks for jumping in, @bubo-py

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
@bubo-py Good work. You're very first step in the Layer5 Community. Small, but significant. 😄

**Pull request merged**
